// require("prismjs/themes/prism.css")
// require("prismjs/themes/prism-coy.css")
// require("prismjs/themes/prism-dark.css")
// require("prismjs/themes/prism-funky.css")
require("prismjs/themes/prism-okaidia.css")
// require("prismjs/themes/prism-solarizedlight.css")
// require("prismjs/themes/prism-tomorrow.css")
// require("prismjs/themes/prism-twilight.css")
// require("./src/styles/prism-customs.css")
require("prismjs/plugins/line-numbers/prism-line-numbers.css")